<?php

/**
 * Implementation of hook_menu().
 */
function cod_api_menu() {
  $items = array();

  $items['cod-api/combined'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => '_cod_api_json_node_list_combined',
  );

  $items['cod-api/%'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => '_cod_api_json_node_list',
    'page arguments' => array(1),
  );
  $items['cod-api/%/%node'] = array(
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'page callback' => '_cod_api_json_node',
    'page arguments' => array(2),
  );

  return $items;
}

/**
 * Query wrapper to return an array of nodes of a given type.
 */
function _cod_api_get_nodes_by_type($type) {
  $nodes = array();

  $query = 'SELECT n.nid FROM {node} n 
            WHERE n.type = "%s" AND n.status = 1
            ORDER BY n.sticky DESC, n.created DESC';
  $result = db_query($query, $type);
  while ($row = db_fetch_object($result)) {
    $node = node_load($row->nid);
    if (!empty($node)) {
      $nodes[] = _cod_api_node_to_json($node);
    }
  }

  return $nodes;
}

/**
 * Prepare a node for rendering to json.
 */
function _cod_api_node_to_json($node) {
  $node->uri = url('cod-api/'. $node->type .'/'. $node->nid, array('absolute' => TRUE));
  drupal_alter('cod_api_node', $node);
  return $node;
}

/**
 * Page callback to render a single node.
 */
function _cod_api_json_node($node) {
  $node = _cod_api_node_to_json($node);

  $data = array(
    $node->type => array($node),
  );

  drupal_set_header("Content-Type: application/json; charset=utf-8");
  print json_encode($data);
  module_invoke_all('exit');
  exit;
}

/**
 * Page callback to render a list of nodes by type.
 */
function _cod_api_json_node_list($type) {
  $data = array(
    $type => _cod_api_get_nodes_by_type($type),
  );

  drupal_set_header("Content-Type: application/json; charset=utf-8");
  print json_encode($data);
  module_invoke_all('exit');
  exit;
}

/**
 * Page callback to render a combined list of nodes grouped by type.
 */
function _cod_api_json_node_list_combined() {
  $data = array(
    'room' => _cod_api_get_nodes_by_type('room'),
    'session' => _cod_api_get_nodes_by_type('session'),
  );

  drupal_set_header("Content-Type: application/json; charset=utf-8");
  print json_encode($data);
  module_invoke_all('exit');
  exit;
}
